Below code is for regression

In [1]:
import socket
import numpy as np
import struct

host = socket.gethostbyname(socket.gethostname())
port = 5060
client_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_server.connect((host, port))
choice=input('to perform regression enter 1, to perform classification enter 2, to perform multi-class classification enter 3: ')
neurons=int(input('enter the number of neurons you want to train the mode in:'))
learning_rate=float(input('enter the learning rate of the model:'))
iter=int(input('enter the number of iterations of the model:'))
X=np.random.random((10,3))
Y=np.random.random((10,1))
array_shapeX = ','.join(map(str, X.shape))
shape_lengthX = str(len(array_shapeX)).ljust(10)  
client_server.send(shape_lengthX.encode('utf-8')) 
client_server.send(array_shapeX.encode('utf-8'))
X_bytes = X.tobytes()
client_server.send(X_bytes)
array_shapeY = ','.join(map(str, Y.shape))
shape_lengthY = str(len(array_shapeY)).ljust(10)  
client_server.send(shape_lengthY.encode('utf-8')) 
client_server.send(array_shapeY.encode('utf-8'))
Y_bytes = Y.tobytes()
client_server.send(Y_bytes)
client_server.send(choice.encode('utf-8'))
client_server.send(struct.pack('i', neurons))
client_server.send(struct.pack('d', learning_rate)) 
client_server.send(struct.pack('i', iter)) 
shape_length_header = client_server.recv(10).decode('utf-8').strip()
shape_length = int(shape_length_header)
shape_array=client_server.recv(shape_length).decode('utf-8')
shape = tuple(map(int, shape_array.split(',')))
array_bits=client_server.recv(np.prod(shape) * 8)
W1=np.frombuffer(array_bits,dtype=np.float64)
print('W1 from server ',host,' is ',W1.reshape(shape))
# Receiving 'W2'
shape_length_header2 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length2 = int(shape_length_header2)
shape_array2 = client_server.recv(shape_length2).decode('utf-8')       # Receive shape
shape2 = tuple(map(int, shape_array2.split(',')))


array_bits2 = client_server.recv(np.prod(shape2) * 8)  
W2 = np.frombuffer(array_bits2, dtype=np.float64)  
print(f'Received W2 with shape: {shape2} and values: {W2.reshape(shape2)}')

# Receiving 'B1'
shape_length_header3 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length3 = int(shape_length_header3)
shape_array3 = client_server.recv(shape_length3).decode('utf-8')       # Receive shape
shape3 = tuple(map(int, shape_array3.split(',')))



array_bits3 = client_server.recv(np.prod(shape3) * 8)  
B1 = np.frombuffer(array_bits3, dtype=np.float64)  
print(f'Received B1 with shape: {shape3} and values: {B1.reshape(shape3)}')
# Receiving 'B2'
shape_length_header4 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length4 = int(shape_length_header4)
shape_array4 = client_server.recv(shape_length4).decode('utf-8')       # Receive shape
shape4 = tuple(map(int, shape_array4.split(',')))



array_bits4 = client_server.recv(np.prod(shape4) * 8)  
B2 = np.frombuffer(array_bits4, dtype=np.float64) 
print(f'Received B2 with shape: {shape4} and values: {B2.reshape(shape4)}')


client_server.close()
W1=W1.reshape(shape)
W2=W2.reshape(shape2)
B1=B1.reshape(shape3)
B2=B2.reshape(shape4)


W1 from server  127.0.1.1  is  [[-0.00451059 -0.00035213  0.01696049]
 [-0.01968284 -0.00509399 -0.00374181]
 [ 0.0170276   0.00397455 -0.0099171 ]
 ...
 [-0.00391221 -0.00903678  0.00635648]
 [-0.00632375 -0.00280699  0.00213903]
 [ 0.0069547   0.00596622 -0.0043461 ]]
Received W2 with shape: (1, 1000) and values: [[ 1.17142275e-02 -1.06117994e-02  8.56857522e-03  2.69047183e-03
   1.04311476e-02  4.52955379e-03 -3.03022850e-03 -4.69613947e-03
  -2.52623185e-02 -2.37154816e-03  8.91165601e-03  4.45923589e-03
  -3.49414995e-03 -1.76939623e-02 -8.67688514e-03 -2.17934571e-02
   5.26222339e-04 -1.61325092e-02 -7.55087559e-05 -1.02854948e-02
  -1.12590370e-02  2.49600456e-02  2.18375050e-03 -3.87746753e-03
   9.36597766e-03  7.54552736e-03  5.69286449e-03 -8.36109928e-03
  -9.98140320e-03 -1.30230438e-02 -1.33788391e-02  2.21670453e-02
  -1.04286539e-03  1.49753275e-02  8.93275261e-03 -8.48579109e-04
  -2.52603760e-03  1.32208699e-03  8.38377219e-03  8.39319714e-03
  -2.12093033e-02  9.23

Below code is for classification

In [4]:
import socket
import numpy as np
import struct

host = socket.gethostbyname(socket.gethostname())
port = 5060
client_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_server.connect((host, port))
choice=input('to perform regression enter 1, to perform classification enter 2, to perform multi-class classification enter 3: ')
neurons=int(input('enter the number of neurons you want to train the mode in:'))
learning_rate=float(input('enter the learning rate of the model:'))
iter=int(input('enter the number of iterations of the model:'))
X=np.random.random((10,3))
Y=np.random.randint(0,2,size=(10,1))
array_shapeX = ','.join(map(str, X.shape))
shape_lengthX = str(len(array_shapeX)).ljust(10)  
client_server.send(shape_lengthX.encode('utf-8')) 
client_server.send(array_shapeX.encode('utf-8'))
X_bytes = X.tobytes()
client_server.send(X_bytes)
array_shapeY = ','.join(map(str, Y.shape))
shape_lengthY = str(len(array_shapeY)).ljust(10)  
client_server.send(shape_lengthY.encode('utf-8')) 
client_server.send(array_shapeY.encode('utf-8'))
Y_bytes = Y.tobytes()
client_server.send(Y_bytes)
client_server.send(choice.encode('utf-8'))
client_server.send(struct.pack('i', neurons))
client_server.send(struct.pack('d', learning_rate)) 
client_server.send(struct.pack('i', iter)) 
shape_length_header = client_server.recv(10).decode('utf-8').strip()
shape_length = int(shape_length_header)
shape_array=client_server.recv(shape_length).decode('utf-8')
shape = tuple(map(int, shape_array.split(',')))
array_bits=client_server.recv(np.prod(shape) * 8)
W1=np.frombuffer(array_bits,dtype=np.float64)
print('W1 from server ',host,' is ',W1.reshape(shape))
# Receiving 'W2'
shape_length_header2 = client_server.recv(10).decode('utf-8').strip()  
shape_length2 = int(shape_length_header2)
shape_array2 = client_server.recv(shape_length2).decode('utf-8')      
shape2 = tuple(map(int, shape_array2.split(',')))



array_bits2 = client_server.recv(np.prod(shape2) * 8)  
W2 = np.frombuffer(array_bits2, dtype=np.float64) 
print(f'Received W2 with shape: {shape2} and values: {W2.reshape(shape2)}')

# Receiving 'B1'
shape_length_header3 = client_server.recv(10).decode('utf-8').strip()  
shape_length3 = int(shape_length_header3)
shape_array3 = client_server.recv(shape_length3).decode('utf-8')      
shape3 = tuple(map(int, shape_array3.split(',')))



array_bits3 = client_server.recv(np.prod(shape3) * 8)  
B1 = np.frombuffer(array_bits3, dtype=np.float64)  
print(f'Received B1 with shape: {shape3} and values: {B1.reshape(shape3)}')
# Receiving 'B2'
shape_length_header4 = client_server.recv(10).decode('utf-8').strip()  
shape_length4 = int(shape_length_header4)
shape_array4 = client_server.recv(shape_length4).decode('utf-8')       
shape4 = tuple(map(int, shape_array4.split(',')))



array_bits4 = client_server.recv(np.prod(shape4) * 8)  
B2 = np.frombuffer(array_bits4, dtype=np.float64)  
print(f'Received B2 with shape: {shape4} and values: {B2.reshape(shape4)}')


client_server.close()
W1=W1.reshape(shape)
W2=W2.reshape(shape2)
B1=B1.reshape(shape3)
B2=B2.reshape(shape4)

W1 from server  127.0.1.1  is  [[ 0.69262516  0.5436337   0.73807228]
 [ 0.77510431  0.13802194  0.4511588 ]
 [ 0.12112483  0.22138395  0.88106541]
 ...
 [ 0.25639655 -0.10386445  0.22521298]
 [ 0.73701264  0.28455494  0.19593525]
 [ 0.20520294 -0.03671594  0.33120494]]
Received W2 with shape: (1, 1000) and values: [[-9.98186217e-02  2.48483810e-02  1.41328099e-01  5.50380622e-01
  -3.56232447e-01  2.75980895e-01  8.22681956e-01  3.51430391e-01
  -1.41112180e-01  7.41136640e-01  6.52133909e-01 -1.74155770e-02
   5.59734407e-01  2.06925064e-01  5.04469305e-01  7.07920533e-01
   4.85596608e-01  3.15830529e-02 -3.93045492e-01 -8.82594588e-02
   6.15168878e-02  5.54399125e-01  2.22483610e-01  3.89086131e-01
  -2.15197766e-01  5.97365555e-01 -3.52595738e-01  5.10165247e-01
  -2.12656648e-02 -5.00222418e-02  5.40026758e-01  1.33938806e-01
   5.18894420e-01  6.75525122e-01  6.58308706e-01 -4.26819404e-01
   3.52283833e-01 -4.09416360e-01 -1.39654916e-01  8.62963788e-01
   3.67067887e-02 -8.20

Below code is for multi-classification

In [5]:
import socket
import numpy as np
import struct

host = socket.gethostbyname(socket.gethostname())
port = 5060
client_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_server.connect((host, port))
choice=input('to perform regression enter 1, to perform classification enter 2, to perform multi-class classification enter 3: ')
neurons=int(input('enter the number of neurons you want to train the mode in:'))
learning_rate=float(input('enter the learning rate of the model:'))
iter=int(input('enter the number of iterations of the model:'))

rows, cols = 10, 4
np.random.seed(4)

Y = np.zeros((rows, cols), dtype=int)


for i in range(rows):
    
    col_index = np.random.randint(0, cols)
    Y[i, col_index] = 1
X=np.random.random((10,7))
array_shapeX = ','.join(map(str, X.shape))
shape_lengthX = str(len(array_shapeX)).ljust(10)  
client_server.send(shape_lengthX.encode('utf-8')) 
client_server.send(array_shapeX.encode('utf-8'))
X_bytes = X.tobytes()
client_server.send(X_bytes)
array_shapeY = ','.join(map(str, Y.shape))
shape_lengthY = str(len(array_shapeY)).ljust(10)  
client_server.send(shape_lengthY.encode('utf-8')) 
client_server.send(array_shapeY.encode('utf-8'))
Y_bytes = Y.tobytes()
client_server.send(Y_bytes)
client_server.send(choice.encode('utf-8'))
client_server.send(struct.pack('i', neurons))
client_server.send(struct.pack('d', learning_rate)) 
client_server.send(struct.pack('i', iter)) 
shape_length_header = client_server.recv(10).decode('utf-8').strip()
shape_length = int(shape_length_header)
shape_array=client_server.recv(shape_length).decode('utf-8')
shape = tuple(map(int, shape_array.split(',')))
array_bits=client_server.recv(np.prod(shape) * 8)
W1=np.frombuffer(array_bits,dtype=np.float64)
print('W1 from server ',host,' is ',W1.reshape(shape))
# Receiving 'W2'
shape_length_header2 = client_server.recv(10).decode('utf-8').strip() 
shape_length2 = int(shape_length_header2)
shape_array2 = client_server.recv(shape_length2).decode('utf-8')     
shape2 = tuple(map(int, shape_array2.split(',')))


array_bits2 = client_server.recv(np.prod(shape2) * 8)  
W2 = np.frombuffer(array_bits2, dtype=np.float64)  
print(f'Received W2 with shape: {shape2} and values: {W2.reshape(shape2)}')

# Receiving 'B1'
shape_length_header3 = client_server.recv(10).decode('utf-8').strip()  
shape_length3 = int(shape_length_header3)
shape_array3 = client_server.recv(shape_length3).decode('utf-8')       
shape3 = tuple(map(int, shape_array3.split(',')))


array_bits3 = client_server.recv(np.prod(shape3) * 8)  
B1 = np.frombuffer(array_bits3, dtype=np.float64)  
print(f'Received B1 with shape: {shape3} and values: {B1.reshape(shape3)}')
# Receiving 'B2'
shape_length_header4 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length4 = int(shape_length_header4)
shape_array4 = client_server.recv(shape_length4).decode('utf-8')       # Receive shape
shape4 = tuple(map(int, shape_array4.split(',')))



array_bits4 = client_server.recv(np.prod(shape4) * 8) 
B2 = np.frombuffer(array_bits4, dtype=np.float64)  
print(f'Received B2 with shape: {shape4} and values: {B2.reshape(shape4)}')


client_server.close()
W1=W1.reshape(shape)
W2=W2.reshape(shape2)
B1=B1.reshape(shape3)
B2=B2.reshape(shape4)

W1 from server  127.0.1.1  is  [[ 0.0046852   0.00995741  0.0104148  ...  0.00420092 -0.00185867
  -0.00824748]
 [-0.00928742 -0.00157685 -0.0017112  ... -0.00390217 -0.00850819
   0.00311288]
 [-0.00898556  0.00245877  0.01039724 ...  0.00727295 -0.00617773
  -0.00999877]
 ...
 [ 0.00446918  0.00844683  0.00818402 ... -0.00213905  0.0002601
   0.00436308]
 [-0.00340187 -0.00569416 -0.0297419  ... -0.01787802 -0.0173442
   0.00234286]
 [ 0.01142007  0.00286538  0.01371526 ...  0.00107368 -0.00114286
  -0.01030313]]
Received W2 with shape: (4, 1000) and values: [[ 4.53408250e-03  1.27193295e-02 -2.51283780e-03 ...  2.20457375e-03
   3.59172472e-03 -1.48048995e-02]
 [-3.10479883e-05  1.49817827e-02  2.17398672e-02 ...  4.81993104e-04
   1.63063204e-02  1.48450439e-02]
 [-4.71668817e-03  6.14857158e-03  7.43311779e-03 ... -2.09650166e-02
   1.97315122e-02 -2.16584492e-03]
 [-1.49605484e-03  2.06837561e-03 -1.22861500e-02 ...  8.51760424e-03
   6.37223199e-03  4.19796967e-03]]
Received B1 