Below code is for regression

In [21]:
import socket
import numpy as np
import struct

host = socket.gethostbyname(socket.gethostname())
port = 5060
client_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_server.connect((host, port))
choice=input('to perform regression enter 1, to perform classification enter 2, to perform multi-class classification enter 3: ')
neurons=int(input('enter the number of neurons you want to train the mode in:'))
learning_rate=float(input('enter the learning rate of the model:'))
iter=int(input('enter the number of iterations of the model:'))
X=np.random.random((10,3))
Y=np.random.random((10,1))
array_shapeX = ','.join(map(str, X.shape))
shape_lengthX = str(len(array_shapeX)).ljust(10)  
client_server.send(shape_lengthX.encode('utf-8')) 
client_server.send(array_shapeX.encode('utf-8'))
X_bytes = X.tobytes()
client_server.send(X_bytes)
array_shapeY = ','.join(map(str, Y.shape))
shape_lengthY = str(len(array_shapeY)).ljust(10)  
client_server.send(shape_lengthY.encode('utf-8')) 
client_server.send(array_shapeY.encode('utf-8'))
Y_bytes = Y.tobytes()
client_server.send(Y_bytes)
client_server.send(choice.encode('utf-8'))
client_server.send(struct.pack('i', neurons))
client_server.send(struct.pack('d', learning_rate)) 
client_server.send(struct.pack('i', iter)) 
shape_length_header = client_server.recv(10).decode('utf-8').strip()
shape_length = int(shape_length_header)
shape_array=client_server.recv(shape_length).decode('utf-8')
shape = tuple(map(int, shape_array.split(',')))
array_bits=client_server.recv(np.prod(shape) * 8)
W1=np.frombuffer(array_bits,dtype=np.float64)
print('W1 from server ',host,' is ',W1.reshape(shape))
# Receiving 'W2'
shape_length_header2 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length2 = int(shape_length_header2)
shape_array2 = client_server.recv(shape_length2).decode('utf-8')       # Receive shape
shape2 = tuple(map(int, shape_array2.split(',')))


array_bits2 = client_server.recv(np.prod(shape2) * 8)  
W2 = np.frombuffer(array_bits2, dtype=np.float64)  
print(f'Received W2 with shape: {shape2} and values: {W2.reshape(shape2)}')

# Receiving 'B1'
shape_length_header3 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length3 = int(shape_length_header3)
shape_array3 = client_server.recv(shape_length3).decode('utf-8')       # Receive shape
shape3 = tuple(map(int, shape_array3.split(',')))



array_bits3 = client_server.recv(np.prod(shape3) * 8)  
B1 = np.frombuffer(array_bits3, dtype=np.float64)  
print(f'Received B1 with shape: {shape3} and values: {B1.reshape(shape3)}')
# Receiving 'B2'
shape_length_header4 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length4 = int(shape_length_header4)
shape_array4 = client_server.recv(shape_length4).decode('utf-8')       # Receive shape
shape4 = tuple(map(int, shape_array4.split(',')))



array_bits4 = client_server.recv(np.prod(shape4) * 8)  
B2 = np.frombuffer(array_bits4, dtype=np.float64) 
print(f'Received B2 with shape: {shape4} and values: {B2.reshape(shape4)}')


client_server.close()
W1=W1.reshape(shape)



W1 from server  127.0.1.1  is  [[-5.71650711e-03 -1.62063948e-02  1.10079359e-02]
 [-7.07720071e-03  2.58218888e-02  8.30990720e-03]
 [-2.16369175e-02 -1.31716747e-02 -3.56582048e-03]
 [ 5.23243224e-03 -8.19026325e-03 -2.27629863e-04]
 [ 2.50206702e-03 -1.03323800e-02 -2.76494045e-03]
 [-3.50413440e-03 -2.10240413e-03 -6.86742729e-03]
 [-8.61704804e-04 -1.48864990e-02 -7.68202685e-03]
 [ 6.25604426e-03  4.05658199e-03  5.09832483e-04]
 [-1.08936720e-02  2.75385896e-02 -5.06303520e-03]
 [-4.18485063e-03  7.34517532e-05 -1.73552908e-03]]
Received W2 with shape: (1, 10) and values: [[-0.00154063  0.0181255  -0.00305455 -0.00062765  0.0141691  -0.01064167
  -0.02706617  0.00296441 -0.00542992 -0.01913398]]
Received B1 with shape: (10, 1) and values: [[-7.35319852e-05]
 [ 4.18013663e-03]
 [ 4.79721928e-05]
 [-8.38750014e-05]
 [ 3.96400991e-03]
 [-2.56137482e-03]
 [-6.62625578e-03]
 [ 5.36533769e-04]
 [-1.75685264e-03]
 [-4.91704976e-03]]
Received B2 with shape: (1, 1) and values: [[0.265980

Below code is for classification

In [22]:
import socket
import numpy as np
import struct

host = socket.gethostbyname(socket.gethostname())
port = 5060
client_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_server.connect((host, port))
choice=input('to perform regression enter 1, to perform classification enter 2, to perform multi-class classification enter 3: ')
neurons=int(input('enter the number of neurons you want to train the mode in:'))
learning_rate=float(input('enter the learning rate of the model:'))
iter=int(input('enter the number of iterations of the model:'))
X=np.random.random((10,3))
Y=np.random.randint(0,2,size=(10,1))
array_shapeX = ','.join(map(str, X.shape))
shape_lengthX = str(len(array_shapeX)).ljust(10)  
client_server.send(shape_lengthX.encode('utf-8')) 
client_server.send(array_shapeX.encode('utf-8'))
X_bytes = X.tobytes()
client_server.send(X_bytes)
array_shapeY = ','.join(map(str, Y.shape))
shape_lengthY = str(len(array_shapeY)).ljust(10)  
client_server.send(shape_lengthY.encode('utf-8')) 
client_server.send(array_shapeY.encode('utf-8'))
Y_bytes = Y.tobytes()
client_server.send(Y_bytes)
client_server.send(choice.encode('utf-8'))
client_server.send(struct.pack('i', neurons))
client_server.send(struct.pack('d', learning_rate)) 
client_server.send(struct.pack('i', iter)) 
shape_length_header = client_server.recv(10).decode('utf-8').strip()
shape_length = int(shape_length_header)
shape_array=client_server.recv(shape_length).decode('utf-8')
shape = tuple(map(int, shape_array.split(',')))
array_bits=client_server.recv(np.prod(shape) * 8)
W1=np.frombuffer(array_bits,dtype=np.float64)
print('W1 from server ',host,' is ',W1.reshape(shape))
# Receiving 'W2'
shape_length_header2 = client_server.recv(10).decode('utf-8').strip()  
shape_length2 = int(shape_length_header2)
shape_array2 = client_server.recv(shape_length2).decode('utf-8')      
shape2 = tuple(map(int, shape_array2.split(',')))



array_bits2 = client_server.recv(np.prod(shape2) * 8)  
W2 = np.frombuffer(array_bits2, dtype=np.float64) 
print(f'Received W2 with shape: {shape2} and values: {W2.reshape(shape2)}')

# Receiving 'B1'
shape_length_header3 = client_server.recv(10).decode('utf-8').strip()  
shape_length3 = int(shape_length_header3)
shape_array3 = client_server.recv(shape_length3).decode('utf-8')      
shape3 = tuple(map(int, shape_array3.split(',')))



array_bits3 = client_server.recv(np.prod(shape3) * 8)  
B1 = np.frombuffer(array_bits3, dtype=np.float64)  
print(f'Received B1 with shape: {shape3} and values: {B1.reshape(shape3)}')
# Receiving 'B2'
shape_length_header4 = client_server.recv(10).decode('utf-8').strip()  
shape_length4 = int(shape_length_header4)
shape_array4 = client_server.recv(shape_length4).decode('utf-8')       
shape4 = tuple(map(int, shape_array4.split(',')))



array_bits4 = client_server.recv(np.prod(shape4) * 8)  
B2 = np.frombuffer(array_bits4, dtype=np.float64)  
print(f'Received B2 with shape: {shape4} and values: {B2.reshape(shape4)}')


client_server.close()
W1=W1.reshape(shape)



W1 from server  127.0.1.1  is  [[ 0.98133369  0.76022586  0.73524822]
 [ 0.39408536  0.45907339  0.23447279]
 [ 0.91330809  0.03084116  0.95686264]
 [-0.11323231  0.1788607   0.56251942]
 [ 0.36975349  0.79782748  0.38591671]
 [ 0.49491242  0.2927931   0.42397798]
 [ 0.12449203  0.32674521  0.59493015]
 [ 0.86907965  0.31854282  0.19847494]
 [-0.06899569  0.57573787  0.35887796]
 [ 0.73114527  0.47014963  0.70152905]]
Received W2 with shape: (1, 10) and values: [[-0.3602981   0.2625924  -0.15169452  0.65214108  0.30350155 -0.21234216
  -0.02773362 -0.19992707  0.74680836 -0.46801776]]
Received B1 with shape: (10, 1) and values: [[ 0.01903988]
 [-0.1831381 ]
 [-0.04024995]
 [-0.28487454]
 [-0.22604294]
 [ 0.02614801]
 [-0.04183203]
 [ 0.00356155]
 [-0.35686322]
 [ 0.10312765]]
Received B2 with shape: (1, 1) and values: [[-0.47142725]]


Below code is for multi-classification

In [23]:
import socket
import numpy as np
import struct

host = socket.gethostbyname(socket.gethostname())
port = 5060
client_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_server.connect((host, port))
choice=input('to perform regression enter 1, to perform classification enter 2, to perform multi-class classification enter 3: ')
neurons=int(input('enter the number of neurons you want to train the mode in:'))
learning_rate=float(input('enter the learning rate of the model:'))
iter=int(input('enter the number of iterations of the model:'))

rows, cols = 10, 4
np.random.seed(4)

Y = np.zeros((rows, cols), dtype=int)


for i in range(rows):
    
    col_index = np.random.randint(0, cols)
    Y[i, col_index] = 1
X=np.random.random((10,7))
array_shapeX = ','.join(map(str, X.shape))
shape_lengthX = str(len(array_shapeX)).ljust(10)  
client_server.send(shape_lengthX.encode('utf-8')) 
client_server.send(array_shapeX.encode('utf-8'))
X_bytes = X.tobytes()
client_server.send(X_bytes)
array_shapeY = ','.join(map(str, Y.shape))
shape_lengthY = str(len(array_shapeY)).ljust(10)  
client_server.send(shape_lengthY.encode('utf-8')) 
client_server.send(array_shapeY.encode('utf-8'))
Y_bytes = Y.tobytes()
client_server.send(Y_bytes)
client_server.send(choice.encode('utf-8'))
client_server.send(struct.pack('i', neurons))
client_server.send(struct.pack('d', learning_rate)) 
client_server.send(struct.pack('i', iter)) 
shape_length_header = client_server.recv(10).decode('utf-8').strip()
shape_length = int(shape_length_header)
shape_array=client_server.recv(shape_length).decode('utf-8')
shape = tuple(map(int, shape_array.split(',')))
array_bits=client_server.recv(np.prod(shape) * 8)
W1=np.frombuffer(array_bits,dtype=np.float64)
print('W1 from server ',host,' is ',W1.reshape(shape))
# Receiving 'W2'
shape_length_header2 = client_server.recv(10).decode('utf-8').strip() 
shape_length2 = int(shape_length_header2)
shape_array2 = client_server.recv(shape_length2).decode('utf-8')     
shape2 = tuple(map(int, shape_array2.split(',')))


array_bits2 = client_server.recv(np.prod(shape2) * 8)  
W2 = np.frombuffer(array_bits2, dtype=np.float64)  
print(f'Received W2 with shape: {shape2} and values: {W2.reshape(shape2)}')

# Receiving 'B1'
shape_length_header3 = client_server.recv(10).decode('utf-8').strip()  
shape_length3 = int(shape_length_header3)
shape_array3 = client_server.recv(shape_length3).decode('utf-8')       
shape3 = tuple(map(int, shape_array3.split(',')))


array_bits3 = client_server.recv(np.prod(shape3) * 8)  
B1 = np.frombuffer(array_bits3, dtype=np.float64)  
print(f'Received B1 with shape: {shape3} and values: {B1.reshape(shape3)}')
# Receiving 'B2'
shape_length_header4 = client_server.recv(10).decode('utf-8').strip()  # Receive shape length
shape_length4 = int(shape_length_header4)
shape_array4 = client_server.recv(shape_length4).decode('utf-8')       # Receive shape
shape4 = tuple(map(int, shape_array4.split(',')))



array_bits4 = client_server.recv(np.prod(shape4) * 8) 
B2 = np.frombuffer(array_bits4, dtype=np.float64)  
print(f'Received B2 with shape: {shape4} and values: {B2.reshape(shape4)}')


client_server.close()
W1=W1.reshape(shape)



W1 from server  127.0.1.1  is  [[ 0.00177627 -0.01809596 -0.00155115  0.0027568   0.0092855  -0.0101134
   0.00083551]
 [-0.00401687  0.00277081  0.00111163 -0.01816111 -0.01059516 -0.00527418
  -0.00206118]
 [-0.00107713 -0.01355508 -0.00823585  0.00868542  0.00234474 -0.00116415
   0.00541714]
 [ 0.00015204  0.00853377  0.00188834  0.00457306 -0.01525607 -0.01243419
  -0.00600278]
 [ 0.02722676  0.01179638  0.01679813 -0.00025712  0.0085259   0.02364853
   0.01316621]
 [ 0.00286503 -0.01748767  0.00173341 -0.0032428  -0.00997883 -0.0154429
   0.01432398]
 [ 0.00702442  0.00053038 -0.00801144 -0.01478296  0.00231621 -0.00713008
  -0.0082692 ]
 [ 0.01674112 -0.00269307  0.00697777  0.01915061  0.00895575 -0.00119436
  -0.02201977]
 [-0.01053798 -0.00021606 -0.01069426 -0.01488678 -0.00426549 -0.01528049
  -0.01031978]
 [-0.00499751 -0.00998227  0.01887767  0.00100652  0.01777746  0.01917012
   0.00103404]]
Received W2 with shape: (4, 10) and values: [[-0.00555894  0.01639834  0.0010560